Feature: Add v3 compatibility
WordImpress/Give-ConvertKit pull request #18
Opened 2023-11-30 05:39 UTC by kjohnson

## Description

This PR introduces a `FormExtension` for compatibility with "v3" forms including the Visual Donation Form Builder and Donation Form templates.

2023-11-30 17:01 UTC, jonwaldstein requested changes

2023-11-30 17:01 UTC, jonwaldstein commented on composer.json
> +            "php": "5.6.40"
should we bump this to php 7.2?

2023-11-30 17:28 UTC, kjohnson commented on src/FormExtension/FormBuilder/Block/edit.tsx
> +}
Ah, there it is. I copy/pasted an example from the codebase. This looks much better.

2023-11-30 17:29 UTC, kjohnson commented on gulpfile.js
> -            domain: 'give-convertkit', //textdomain
Ah, yeah, it looks like there aren't any Github actions setup on this repo. The last commit was in 2019 😅

2023-11-30 17:31 UTC, kjohnson commented on src/FormExtension/FormBuilder/Block/edit.tsx
> +                    <div className={'givewp-mailchimp-controls'}>
Yup - missed that one.

2023-11-30 17:43 UTC, kjohnson commented on composer.json
> +            "php": "5.6.40"
Give core sets `7.2`, so the add-ons can't support any lower. I'll update it.

2023-11-30 17:59 UTC, kjohnson commented on src/FormExtension/Actions/RenderDonationFormBlock.php
> +            ->scope(function(ConvertKitField $field, $value, Donation $donation) {
Worth a discussion. The action scheduler comes with its own set of trade-offs. Alternatively, we could make these non-`blocking`, since we aren't using the response anyway.

2023-11-30 20:08 UTC, jonwaldstein commented on src/FormExtension/Actions/RenderDonationFormBlock.php
> +            ->scope(function(ConvertKitField $field, $value, Donation $donation) {
@kjohnson what happens if the request fails though?  I would think we want to confirm the request was successful or else notify/log that it wasn't.  Even the legacy implementation is checking for `is_wp_error`.

I would also be concerned that if we're not waiting for the response to resolve, the page could refresh and the request could be canceled.

I think action scheduler would solve all of these concerns for us.

2023-11-30 21:19 UTC, kjohnson commented on src/FormExtension/Actions/RenderDonationFormBlock.php
> +            ->scope(function(ConvertKitField $field, $value, Donation $donation) {
While the v2 implementation does check for `is_wp_error`, it does nothing with that response. At most, the `subscribe_email` _does_ return a `bool` value but that return value is never used.

```php
// Success!
if ( ! is_wp_error( $request ) && 200 == wp_remote_retrieve_response_code( $request ) ) {
	// @TODO: Write to donation payment notes
	$return = true;
}
```

I agree that we could improve upon v2, but the goal here is to introduce compatibility.

2023-11-30 21:34 UTC, jonwaldstein commented on src/FormExtension/Actions/RenderDonationFormBlock.php
> +            ->scope(function(ConvertKitField $field, $value, Donation $donation) {
since we're dealing with an external api request, let's at least log any errors for good measure - then I think it's fair to circle back to implement action scheduler to improve this flow.  how does that sound?

2023-11-30 22:05 UTC, kjohnson commented on src/FormExtension/Actions/RenderDonationFormBlock.php
> +            ->scope(function(ConvertKitField $field, $value, Donation $donation) {
That is fair. I pushed some logging for failed requests. See https://github.com/impress-org/give-convertkit/pull/18/commits/bf95fa2391eda3533c23651d1b6d74821fe2aace

2023-11-30 22:29 UTC, jonwaldstein approved these changes
Great job man! Ready for QA 🌈

2023-12-04 19:00 UTC, kjohnson commented on src/FormExtension/Actions/EnqueueDonationFormScripts.php
> +        wp_enqueue_script('givewp-form-extension-mailchimp', $this->scriptSrc, $this->scriptAsset['dependencies']);
```suggestion
        wp_enqueue_script('givewp-form-extension-convertkit', $this->scriptSrc, $this->scriptAsset['dependencies']);
```

2023-12-04 19:00 UTC, kjohnson commented on src/FormExtension/Actions/EnqueueDonationFormScripts.php
> +        wp_enqueue_style('givewp-form-extension-mailchimp', $this->styleSrc);
```suggestion
        wp_enqueue_style('givewp-form-extension-convertkit', $this->styleSrc);
```

2023-12-11 15:19 UTC, kjohnson commented
Build: https://github.com/impress-org/give-convertkit/actions/runs/7169535516

2024-05-06 15:16 UTC, rickalday approved these changes
Passed manual QA tests.

2024-05-06 15:54 UTC, merged